### ISSUE TITLE
Allow grouping of variants into arbitrary categories

### ISSUE THREAD

**Issue by sambaxter** [broadinstitute/genetic-prevalence-estimator#167]
This is not super high priority but would be great for v1.1 or v2.

I would love to be able to allow users to arbitrarily group variants via a drop down that they could customize the labels.  I think its best to give them a max of 4 groups to start.  Similar to "source" we would  add a toggle that lets them visualize the relative contributions of these groups to the carrier frequency.  

Longer term we may also be able to provide some customization to the prevalence model based on the grouping.  For example individuals have to compound het for group 1 and group 2 or homozygous for group 3. We have already needed to do this for a few groups so we are making progress on the math so depending on when we get this first part done we can decide whether we would do a 2 stage release or release both of these functionalities at once.

**Comment by rileyhgrant** [comment]
Allow for 'tagging' of variants with somewhere up to 4-5 arbitrary tags, these tags can then be filtered on to perform calculations, maybe in different combinations (tag A * tag B, or (tag A + tag B) * tag C) etc. 

Some key value pair method for tagging variants that gets stored to the backend, that could then be used in calculations on the frontend in a variety of ways could work.

Note: when getting into this, asking Sam about how she does this in her excel sheets, that would likely be illustrative of what kind of transformations we actually want to do.

**Comment by rileyhgrant** [comment]
Related #125
