### ISSUE TITLE
deselect of all variants doesn't work - reverts to selecting all each time

### ISSUE THREAD

**Issue by sambaxter** [broadinstitute/genetic-prevalence-estimator#268]
The deselect all button for the variant table doesn't seem to be working correctly (across all lists I've tried).  If you uncheck variants it will select all, but if all variants are selected and you try to deselect, it will unselect them and then reselect them all every time.  

<img width="233" alt="image" src="https://github.com/broadinstitute/genetic-prevalence-estimator/assets/19212392/1ae08caa-b444-4460-a1b7-1868f7dc0d2a">

**Comment by rileyhgrant** [comment]
Hm, ok this seems a bit niche, but is notable it's a problem.

The behavior to select all variants if none are selected was added as a workaround to allow for saving of calculations to the database on the initial creation of a list. 

Will have to re-think how to allow both these pieces of functionality to work correctly.

**Comment by sambaxter** [comment]
The behavior to select/deselect all variants was requested/added separately of the issue with the async behavior.  We often use the deselect everything so we can quickly isolate a couple variants and check the frequency of just those.  Without that we would need to deselect everyone individually which can be really tedious in longer lists. We can cht about this in the next meeting but it would be nice to have this work.
