### ISSUE TITLE
Gene link on genie list page going to v3 not v4

### ISSUE THREAD

**Issue by sambaxter** [broadinstitute/genetic-prevalence-estimator#289]
The link next to the gene name on v4.1 genie lists goes to v3, not v4.  [See this example of a recent list I made ](https://genie.broadinstitute.org/variant-lists/9942185a-0f64-46f6-af47-4dee7d750cf6/)
![image](https://github.com/user-attachments/assets/a963c6de-f1a1-4a9e-b154-e928239cd8ba)

**Comment by rileyhgrant** [comment]
Resolved by #278 

I had merged that, but not deployed the changes yet -- oops. The changes are now deployed.
