### ISSUE TITLE
Allow filtering variant table on ID

### ISSUE THREAD

**Issue by sambaxter** [broadinstitute/genetic-prevalence-estimator#294]
When you added scrolling on the variant table I lost the ability to search for a variant using the internet browser search function.  I am assuming this is because not all variants are displayed on the screen at all times anymore.  To solve for this can we add a search field like the one on the gnomAD gene page variant table, which takes you to the spot on the list where the variant is and highlights it?  Also same as gnomAD we should allow for searching on p., c., and gnomAD ID

**Comment by rileyhgrant** [comment]
From meeting:

It would be beneficial to have the list jump to the variant and keep some of the context. Implementing this as more of a 'jump to' with a highlight of the partial search term. If this becomes a huge rabbit whole, we could just filter the list, then come back to the 'jump to' functionality at a later date
